### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by minhbang** [ViRb3/cloudflare-warp-wireguard-client#2] opened 2020-03-13 00:54 UTC
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.cloudflareclient.com/v0a769/reg

**Comment by ViRb3** [comment] 2020-03-13 15:15
Works just fine here. Please give more details.

**Comment by jashsayani** [comment] 2020-03-13 23:42
Same issue:
```
Traceback (most recent call last):
  File "main.py", line 174, in <module>
    account_data = do_register()
  File "main.py", line 87, in do_register
    response.raise_for_status()
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.cloudflareclient.com/v0a769/reg

```

**Comment by ViRb3** [comment] 2020-03-15 00:06
Maybe the API version is being gradually deprecated. I will try to see if there's a new one.

**Comment by ViRb3** [comment] 2020-03-17 00:26
I have pushed an update with the current (at least for me) API version on Android. Can you please confirm if everything works now?

**Comment by AmiiirCom** [comment] 2020-03-17 05:32
> I have pushed an update with the current (at least for me) API version on Android. Can you please confirm if everything works now?

hey dude, I tested it. problem fixed.

**Comment by B4TT3RY** [comment] 2020-03-17 08:13
```
Traceback (most recent call last):
  File "main.py", line 171, in <module>
    account_data = do_register()
  File "main.py", line 85, in do_register
    response.raise_for_status()
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.cloudflareclient.com/v0a848/reg
```

**Comment by AmiiirCom** [comment] 2020-03-17 20:47
> ```
> Traceback (most recent call last):
>   File "main.py", line 171, in <module>
>     account_data = do_register()
>   File "main.py", line 85, in do_register
>     response.raise_for_status()
>   File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.cloudflareclient.com/v0a848/reg
> ```

I tried again. I guess the problem is on your side. I want you to try it again, please. We look forward to your success.

**Comment by ViRb3** [comment] 2020-03-30 14:11
The newest app update finally landed on my Android phone. I am planning to update this project to use the new API in order to support #6. Let's see if you still get error 403 after that.

**Comment by LuuOW** [comment] 2020-04-06 16:17
Plz can you guide me how to see the those API calls to get the licence key

**Comment by ViRb3** [comment] 2020-04-08 20:17
@minhbang @jashsayani @AmiiirCom @B4TT3RY can you please confirm if you are still experiencing an error 403 after the latest update?

@TheHarryOn sorry for not responding earlier here or at the PR, I've been really busy with a few other projects. If you still have any problems feel free to ask away.

**Comment by LuuOW** [comment] 2020-04-08 20:29
> @minhbang @jashsayani @AmiiirCom @B4TT3RY can you please confirm if you are still experiencing an error 403 after the latest update?
> 
> @TheHarryOn sorry for not responding earlier here or at the PR, I've been really busy with a few other projects. If you still have any problems feel free to ask away.

I get the licence key without problems doing the GET request to the API, no errors I use the following version of the API 
https://api.cloudflareclient.com/v0a848/reg/abXXXX0ac-1XX1-4ffc-bXXX2-5XXXXX7c/account

And using the access_token as bearer token
Btw no problems about response, I fix it up ty

**Comment by ViRb3** [comment] 2020-04-08 21:06
@TheHarryOn That's the same endpoint used in this script, so I assume it works for you too now?

**Comment by AmiiirCom** [comment] 2020-04-08 21:27
> @minhbang @jashsayani @AmiiirCom @B4TT3RY can you please confirm if you are still experiencing an error 403 after the latest update?
> 
> @TheHarryOn sorry for not responding earlier here or at the PR, I've been really busy with a few other projects. If you still have any problems feel free to ask away.

tried it and me no problem. I hope fixed.

**Comment by LuuOW** [comment] 2020-04-09 00:33
> @TheHarryOn That's the same endpoint used in this script, so I assume it works for you too now?

Yes

**Comment by ViRb3** [comment] 2020-04-09 13:36
I am closing this issue assuming the problem is fixed. If anybody still gets an error 403, please comment below and I will re-open.

**Closed as completed by ViRb3** 2020-04-09 13:36 UTC
Labels: bug
